kkusikkusi/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.reindex, name='reindex'),
    
    path('intro_adopt/', views.intro_adopt, name='intro_adopt'),
    path('req_adopt/', views.req_adopt, name='req_adopt'),
    path('intro1/', views.intro1, name='intro1'),
    path('intro2/', views.intro2, name='intro2'),
    path('intro3/', views.intro3, name='intro3'),
    
    path('cands/', views.cands, name='cands'),
    path('cand/<int:cand_id>/', views.cand, name='cand'),
    path('posts/', views.posts, name='posts'),
    path('post/<int:post_id>/', views.post, name='post'),
    
    
]

website/models.py
from django.db import models

def image_path(instance, filename):
    from random import choice
    import string
    
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    extension = filename.split('.')[-1]
    
    return 'images/%s.%s' % (pid, extension)
        
PROTECTOR_CHOICES = (
    ('1', '임시보호자'),
    ('2', '입양자'),
    ('3', '임보&입양자'),
    ('4', '기타')
)        

GENDER_CHOICES = (
    ('M', '남'),
    ('F', '여'),
    ('Q', '미상'),
)

CANDS_STATUS = (
    ('1', '보호중'),
    ('2', '가정임보중'),
    ('3', '입양예약'),
    ('4', '입양완료')
)
        
class Protector(models.Model):
    name = models.CharField(max_length=10, verbose_name='이름')
    type = models.CharField(max_length=2, choices=PROTECTOR_CHOICES, null=True, blank=True, verbose_name='보호타입')
    
    phone_number = models.CharField(max_length=11, null=True, blank=True, verbose_name='전화번호')
    address = models.CharField(max_length=100, null=True, blank=True, verbose_name='주소')
    
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES, null=True, blank=True, verbose_name='성별')
    age = models.IntegerField(null=True, blank=True, verbose_name='나이')
    memo = models.TextField(null=True, blank=True, verbose_name='기타 메모')
    
    naver_id = models.CharField(max_length=20, null=True, blank=True, verbose_name='네이버 ID')
    nickname = models.CharField(max_length=20, null=True, blank=True, verbose_name='닉네임')
    insta_id = models.CharField(max_length=20, null=True, blank=True, verbose_name='인스타 ID')
    
    def __str__(self):
        return self.name
        
    class Meta:
        verbose_name_plural = "보호자"

class Candidate(models.Model):
    name = models.CharField(max_length=10, verbose_name='이름')
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES, null=True, blank=True, verbose_name='성별')
    kind = models.CharField(max_length=20, null=True, blank=True, verbose_name='종')
    # birth_year = models.IntegerField(null=True, , verbose_name='')
    age = models.CharField(max_length=20, blank=True, verbose_name='나이')
    neutering = models.BooleanField(null=True, blank=True, verbose_name='중성화 여부')
    
    # adopted = models.BooleanField(verbose_name='입양완료여부')
    adopted = models.CharField(max_length=2, choices=CANDS_STATUS, null=True, blank=True, verbose_name='보호상태')
    protector = models.ForeignKey(Protector, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='보호자')
    
    image = models.ImageField(upload_to=image_path, null=True, blank=True, verbose_name='대표사진')
    
    reg_date = models.DateTimeField(auto_now_add = True, verbose_name='등록일자')
    adopt_date = models.DateTimeField(null=True, blank=True, verbose_name='입양날짜')
    
    memo = models.TextField(null=True, blank=True, verbose_name='기타 메모')
    
    def __str__(self):
        return self.name
        
    class Meta:
        verbose_name_plural = "토끼 목록"
        
# class User(models.Model):
    
class Post(models.Model):
    # user = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default='알 수 없는 사용자')
    title = models.CharField(max_length=30, verbose_name='제목')
    content = models.TextField(verbose_name='내용', null=True, blank=True)
    
    cand = models.ForeignKey(Candidate, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='토끼')

    hide_yn = models.BooleanField(verbose_name='숨김여부')

    pub_date = models.DateTimeField(auto_now_add = True, verbose_name='등록날짜')
    mod_date = models.DateTimeField(auto_now_add = True, verbose_name='수정날짜')
    
    def __str__(self):
        return self.title
        
    class Meta:
        verbose_name_plural = "입양 홍보글"
    
class Photo(models.Model):
    post = models.ForeignKey(Post, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(upload_to=image_path, null=True, blank=True)

website/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.paginator import Paginator
from .models import Candidate, Post, Photo
from .models import GENDER_CHOICES, CANDS_STATUS
    
def index(request):
    return render(request, 'website/index.html')
    
def reindex(request):
    return redirect(index)
        
def intro1(request):
    return render(request, 'website/intro1.html')
    
def intro2(request):
    return render(request, 'website/intro2.html')
    
def intro3(request):
    return render(request, 'website/intro3.html')

def intro_adopt(request):
    return render(request, 'website/intro_adopt.html')
    
def req_adopt(request):
    return render(request, 'website/req_adopt.html')
    
def convert_cand(candidates):
    for cand in candidates:
        if cand.gender == 'M':
            cand.gender = '남아'
        elif cand.gender == 'F':
            cand.gender = '여아'
        elif cand.gender == 'Q':
            cand.gender = '미상'
            
        if cand.adopted is not None:
            cand.adopted = CANDS_STATUS[int(cand.adopted)-1][1]
            
        if cand.neutering is True:
            cand.neutering = 'O'
        elif cand.neutering is False:
            cand.neutering = 'X'
        else:
            cand.neutering = '미상'
            
    return candidates

def cands(request):
    page = request.GET.get('page', '1')  
    candidates = Candidate.objects.exclude(adopted__in=['3', '4'])
    candidates = convert_cand(candidates)
    paginator = Paginator(candidates, 9)
    candidates_page = paginator.get_page(page)
    return render(request, 'website/cands.html', {'candidates_page': candidates_page})
    
def cand(request, cand_id):
    cand = Candidate.objects.get(id=cand_id)
    cand = convert_cand([cand])[0]
    
    posts = Post.objects.filter(cand=cand_id)
    
    # photos = Photo.objects.select_related('post').filter(post_id__in=post_id)
    # photos = Photo.objects.filter(post__in=posts)
    
    post_sets = []
    
    for post in posts:
        test = {}
        test['post'] = post
        test['photos'] = Photo.objects.filter(post = post)
        post_sets.append(test)
    
    print(post_sets)

    return render(request, 'website/cand.html',  {'cand': cand, 'post_sets': post_sets})

def posts(request):
    page = request.GET.get('page', '1')  
    posts = Post.objects.all()
    paginator = Paginator(posts, 9)
    posts_page = paginator.get_page(page)

    for post in posts_page.object_list:
        post.photo = Photo.objects.filter(post = post)[0]
    
    return render(request, 'website/posts.html', {'posts_page': posts_page})

def post(request, post_id):
    post = Post.objects.get(id=post_id)
    post.photo = Photo.objects.filter(post = post)
    related_posts = Post.objects.filter(cand=post.cand.id).exclude(id = post_id)
    return render(request, 'website/post.html', {'post': post, 'related_posts':related_posts})
    

website/templates/website/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>꾸시꾸시 &mdash; 토끼보호소</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link href="https://fonts.googleapis.com/css?family=Oswald:400,700|Work+Sans:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'neos-master/fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'neos-master/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'neos-master/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'neos-master/css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'neos-master/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'neos-master/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'neos-master/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'neos-master/css/animate.css' %}">    
    
    <link rel="stylesheet" href="{% static 'neos-master/fonts/flaticon/font/flaticon.css' %}">
  
    <link rel="stylesheet" href="{% static 'neos-master/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'neos-master/css/style.css' %}">
	
	<link rel="stylesheet" href="{% static 'custom/custom.css' %}">
    
  </head>
  
  <body>
  
	<!--<div id="overlayer"></div>-->
	<!--<div class="loader">
		<div class="spinner-border text-primary" role="status">
			<span class="sr-only">Loading...</span>
		</div>
	</div>-->

	<div class="site-wrap">

		<div class="site-mobile-menu">
		  <div class="site-mobile-menu-header">
			<div class="site-mobile-menu-close mt-3">
			  <span class="icon-close2 js-menu-toggle"></span>
			</div>
		  </div>
		  <div class="site-mobile-menu-body"></div>
		</div> <!-- .site-mobile-menu -->
		
		
		<div class="site-navbar-wrap js-site-navbar bg-white">
		  
		  <div class="container">
			<div class="site-navbar bg-light">
			  <div class="row align-items-center">
				<div class="col-2">
				  <h2 class="mb-0 site-logo"><a href="{% url 'website:index' %}" class="font-weight-bold text-uppercase">KUSIKUSI</a></h2>
				  <!--<h2 class="mb-0 site-logo"><a href="{% url 'website:index' %}" class="font-weight-bold text-uppercase">
					<img src="{% static 'images/kkusikkusi_logo_sm.png' %}" style="width: 70%;"/>
				  </a></h2>-->
				</div>
				<div class="col-10">
				  <nav class="site-navigation text-right" role="navigation">
					<div class="container">
					  <div class="d-inline-block d-lg-none ml-md-0 mr-auto py-3"><a href="#" class="site-menu-toggle js-menu-toggle text-black"><span class="icon-menu h3"></span></a></div>

					  <ul class="site-menu js-clone-nav d-none d-lg-block">
						<li><a href="{% url 'website:index' %}">Home</a></li>
						<li class="has-children">
						  <a href="#">소개</a>
						  <ul class="dropdown arrow-top">
							<li><a href="{% url 'website:intro1' %}">토끼보호연대</a></li>
							<li><a href="{% url 'website:intro2' %}">꾸시꾸시</a></li>
							<li><a href="{% url 'website:intro3' %}">오시는 길</a></li>
							<!--<li class="has-children">
							  <a href="#">Sub Menus</a>
							  <ul class="dropdown">
								<li><a href="testimonials.html">Testimonials</a></li>
								<li><a href="gallery.html">Gallery</a></li>
								<li><a href="why-choose-us.html">Why Choose Us</a></li>
							  </ul>
							</li>-->
						  </ul>
						</li>
						<!--<li><a href="{% url 'website:intro_adopt' %}">입양안내</a></li>-->
						<li class="has-children">
							<a href="#">입양안내</a>
							<ul class="dropdown arrow-top">
								<li><a href="{% url 'website:intro_adopt' %}">입양조건</a></li>
								<li><a href="{% url 'website:req_adopt' %}">입양신청</a></li>
							</ul>
						</li>
						<li class="has-children">
							<a href="#">책임입양</a>
							<ul class="dropdown arrow-top">
								<li><a href="{% url 'website:cands' %}">토끼목록</a></li>
								<li><a href="{% url 'website:posts' %}">토끼자랑</a></li>
							</ul>
						</li>
						<!--<li><a href="#">입양완료</a></li>-->
						<li><a href="https://instagram.com/kusikusi_cafe" target="_blank">인스타 <i class="icon-instagram"></i></a></li>
						<!--<li><a href="https://cafe.naver.com/pultodong" target="_blank"><span class="d-inline-block bg-primary text-white btn btn-primary">네이버카페</span></a></li>-->
						<li class="active"><a href="https://cafe.naver.com/pultodong" target="_blank">네이버카페</a></li>
					  </ul>
					</div>
				  </nav>
				</div>
			  </div>
			</div>
		  </div>
		</div>
		
		<div class="slant-1"></div>
		
		<div class="site-section first-section" data-aos="fade">
		  <div class="container">
		
		{% block content %}
		{% endblock %}
		  </div>
		</div>
		
		<footer class="site-footer bg-dark" style="padding: 1em 0;">
		  <div class="container">
			
			<div class="row pt-5 mt-5 text-center">
			  <div class="col-md-12">
				<p>
				<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
				Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
				<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
				</p>

				
			  </div>
			  
			</div>
		  </div>
		</footer>
		
	</div> <!-- site-wrap -->
	
  <script src="{% static 'neos-master/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'neos-master/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'neos-master/js/jquery-ui.js' %}"></script>
  <script src="{% static 'neos-master/js/popper.min.js' %}"></script>
  <script src="{% static 'neos-master/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'neos-master/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'neos-master/js/jquery.stellar.min.js' %}"></script>

  <script src="{% static 'neos-master/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'neos-master/js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'neos-master/js/aos.js' %}"></script>

  <script src="{% static 'neos-master/js/main.js' %}"></script>
  
  <script src="{% static 'custom/custom.js' %}"></script>

  </body>
</html>

website/templates/website/cand.html
{% extends "website/base.html" %}

{% block content %}
	
	<div class="col-md-12 text-center" data-aos="fade">
	<span class="caption d-block mb-2 font-secondary font-weight-bold">상세정보</span>
		<h2 class="site-section-heading text-uppercase text-center font-secondary">{{ cand.name }}</h2>
    </div>
	
	<div class="row mt-4">
		<div class="col-md-12 col-lg-12 mb-4" data-aos="fade-up" data-aos-delay="">
			<!--<div style="width: 600px; margin: 0 auto;">-->
			<div style="max-width: 600px; margin: 0 auto;">
				<img src="{{ cand.image.url }}" alt="Image" class="img-fluid">
			</div>
		</div>
		<!-- <div class="col-md-12 col-lg-12 mb-4" data-aos="fade-up" data-aos-delay="">
			<ul>
				<li>성별: {{ cand.gender }}</li>
				<li>종: {{ cand.kind }}</li>
				<li>나이: {{ cand.age }}</li>
				<li>중성화여부: {{ cand.neutering }}</li>
				<li>보호상태: {{ cand.adopted }}</li>
				<li>보호자: {{ cand.protector }}</li>
				<li>등록일: {{ cand.reg_date }}</li>
			</ul>
		</div> -->

		<div class="col-md-12 col-lg-12 mb-4" data-aos="fade-up" data-aos-delay="">
			<div style="max-width: 600px; margin: 0 auto;">
			<!--<div style="width: 600px; margin: 0 auto;">-->
				<table class="type05 text-center">
					<tr>
						<th scope="row">성별</th>
						<td>{{ cand.gender }}</td>
					</tr>
					<tr>
						<th scope="row">나이</th>
						<td>{{ cand.age }}</td>
					</tr>
					<tr>
						<th scope="row">중성화여부</th>
						<td>{{ cand.neutering }}</td>
					</tr>
					<tr>
						<th scope="row">보호상태</th>
						<td>{{ cand.adopted }}</td>
					</tr>
					<tr>
						<th scope="row">보호자</th>
						<td>{{ cand.neutering }}</td>
					</tr>
					<tr>
						<th scope="row">등록일</th>
						<td>{{ cand.reg_date }}</td>
					</tr>
				</table>
			</div>
			
		</div>
		
	</div>
	
	<div class="col-md-12 text-center mt-4" data-aos="fade">
		<span class="caption d-block mb-2 font-secondary font-weight-bold">{{ cand.name }}관련 글 모음</span>
		<h2 class="site-section-heading text-uppercase text-center font-secondary"></h2>
    </div>
	
	{% for post_set in post_sets %}
	<div class="row mt-4">
		<div class="col-md-12 text-center mb-3 mb-md-0">
			<h4 class="text-uppercase mb-4">{{ post_set.post }}</h4>
		</div>
	</div>
	{% endfor %}
	
	<ul>
		
			<li>{{ post_set.post }}
			{% for photo in post_set.photos %}
				<img src="{{ photo.image.url }}" alt="Image" class="img-fluid" style="width: 400px;">
			{% endfor %}
			</li>
		
	</ul>
{% endblock %}

website/templates/website/cands.html
{% extends "website/base.html" %}

{% block content %}
	<div class="row mb-5">
		<div class="col-md-12 text-center" data-aos="fade">
			<span class="caption d-block mb-2 font-secondary font-weight-bold">토끼목록</span>
			<h2 class="site-section-heading text-uppercase text-center font-secondary">보호 중인 토끼들입니다</h2>
		</div>
	</div>
	
	<div  class="row border-responsive">
		{% for candidate in candidates_page.object_list %}
			<div class="col-md-6 col-lg-4 mb-5">
				<a href="{% url 'website:cand' candidate.id %}">
					<div class="media-image">
					  <img src="{{ candidate.image.url }}" alt="Image" class="img-fluid">
					  <div class="media-image-body">
						<h2 class="font-secondary text-uppercase">{{ candidate.name }}</h2>
						<span class="d-block mb-3">{{ candidate.gender }} | {{ candidate.age}} </span>
					  </div>
					</div>
				</a>
			</div>
		  {% endfor %}
	</div>

	<ul class="pagination justify-content-center">
        {% if candidates_page.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ candidates_page.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        {% for page_number in candidates_page.paginator.page_range %}
            {% if page_number == candidates_page.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if candidates_page.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ candidates_page.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
	
{% endblock %}

website/templates/website/old/base.html
{% load static %}

<html lang="en">
	<head>
		<title>꾸시꾸시</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="{% static 'bootstrap-4.5.2-dist/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'custom/css/custom.css' %}">
		
		<link rel="stylesheet" href="{% static  'css/open-iconic-bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static  'css/animate.css' %}">
		
		<link rel="stylesheet" href="{% static  'css/owl.carousel.min.css' %}">
		<link rel="stylesheet" href="{% static  'css/owl.theme.default.min.css' %}">
		<link rel="stylesheet" href="{% static  'css/magnific-popup.css' %}">

		<link rel="stylesheet" href="{% static  'css/aos.css' %}">

		<link rel="stylesheet" href="{% static  'css/ionicons.min.css' %}">

		<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
		<link rel="stylesheet" href="{% static  'css/jquery.timepicker.css' %}">

		
		<link rel="stylesheet" href="{% static  'css/flaticon.css' %}">
		<link rel="stylesheet" href="{% static  'css/icomoon.css' %}">
		<link rel="stylesheet" href="{% static  'css/style.css' %}">
		
		<!-- jquery -->
		<script src="{% static 'bootstrap-4.5.2-dist/js/bootstrap.bundle.min.js' %}"></script>
	</head>

	<body>
		<div class="container">
			<div id="colorlib-page">
				<aside id="colorlib-aside" role="complementary" class="js-fullheight text-center">
					<h1 id="colorlib-logo"><a href="{% url 'website:index' %}"><span class="flaticon-camera"></span>꾸시꾸시</a></h1> <!-- icon 넣는 부분 -->
					<nav id="colorlib-main-menu" role="navigation">
						<ul>
							<li><a href="{% url 'website:cands' %}">토끼목록</a></li>
							<li><a href="{% url 'website:posts' %}">입양홍보</a></li>
							<li><a href="{% url 'website:notice' %}">입양절차</a></li>
						</ul>
					</nav>

					<div class="colorlib-footer">
						<h3>관련 SNS</h3>
						<div class="d-flex justify-content-center">
							<ul class="d-flex align-items-center">
								<li class="d-flex align-items-center jusitfy-content-center"><a href="https://instagram.com/kusikusi_cafe"><i class="icon-instagram"></i></a></li>
							</ul>
						</div>
					</div>
				</aside>
				
				<div id="colorlib-main">
					{% block content %}
					{% endblock%}
				</div>
			</div> <!-- colorlib-page -->
			
		</div> <!-- container -->
	</body>

</html>

website/templates/website/old/cand.html
{% extends "website/base.html" %}

{% block content %}
	1. 토끼 정보
	이름: {{ cand.name }}
	<br>
	출생연도: {{ cand.birth_year }}
	
	<br><br>2. 관련 게시물
	
	{% for post in posts %}
		<br>-{{ post.title }}
	{% endfor %}
{% endblock %}

website/templates/website/old/cands.html
{% extends "website/base.html" %}

{% block content %}
<section class="ftco-section-2">
	<div class="photograhy">
		<div class="row no-gutters">
			{% for candidate in candidates %}
				<div class="col-md-4 ">
					<a href="{% url 'website:cand' candidate.id %}" class="photography-entry img image-popup d-flex justify-content-center align-items-center" style="background-image: url({{candidate.image.url}});">
						<div class="overlay"></div>
						<div class="text text-center">
							<h3>{{ candidate.name }}</h3>
						</div>
					</a>
				</div>
			{% endfor %}
		</div>
	</div>
</section>
{% endblock %}

website/templates/website/old/index.html
{% extends "website/base.html" %}

{% block content %}
	홈화면
{% endblock %}

website/templates/website/old/notice.html
{% extends "website/base.html" %}

{% block content %}
입양 조건

1. 입양계약서를 작성합니다.

2. 입양 결정 전 가정 방문에 동의해 주셔야 합니다. (기존 반려토끼가 있는 가정의 경우, 카페나 SNS 활동 내역 공개 등을 통해 대체 확인 가능합니다.)

3. 입양 후 7일 내에 카페(https://cafe.naver.com/pultodong)에 입양 후기를 작성하며, 입양 후 6개월동안, 매월 1회 이상 카페에 아이의 소식을 게시해 주세요.

4. 사람과 같은 실내 공간에서 지내도록 해 주세요. (베란다, 옥상, 마당, 케이지, 뜬장 등 절대 불가)

5. 토끼의 특성에 맞는 먹이, 환경, 진료 등을 제공해주세요.

6. 입양된 토끼는 반려동물 외 다른 목적으로 이용하지 않습니다. (체험학습, 전시, 영리 추구, 가축 등 절대 불가)

.. 기타등등
{% endblock %}

website/templates/website/old/posts.html
{% extends "website/base.html" %}

{% block content %}
	게시판 형태로 만들기
	<ol>
		{% for post in posts %}
			<li>
				{{ post.title }}
			</li>
			{% for photo in post.photo_set.all %}
				<img src="{{photo.image.url}}">
			{% endfor %}
		{% endfor %}
	</ol>
{% endblock %}

website/templates/website/posts.html
{% extends "website/base.html" %}

{% block content %}
	<div class="row mb-5">
		<div class="col-md-12 text-center" data-aos="fade">
			<span class="caption d-block mb-2 font-secondary font-weight-bold">토끼자랑</span>
			<h2 class="site-section-heading text-uppercase text-center font-secondary">보호 중인 토끼에 대한 글입니다</h2>
	  </div>
	</div>
	
	<div  class="row border-responsive">
		{% for post in posts_page.object_list %}
			<div class="col-md-6 col-lg-4 mb-5">
				<a href="{% url 'website:post' post.id %}">
					<div class="media-image">
					  <img src="{{ post.photo.image.url }}" alt="Image" class="img-fluid">
					  <div class="media-image-body">
						<h2 class="font-secondary text-uppercase">{{ post.title }}</h2>
						<p>{{post.cand}}</p>
						<p>{{post.pub_date}}</p>
					  </div>
					</div>
				</a>
			</div>
		  {% endfor %}
	</div>

	<ul class="pagination justify-content-center">
        {% if posts_page.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ posts_page.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        {% for page_number in posts_page.paginator.page_range %}
            {% if page_number == posts_page.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if posts_page.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ posts_page.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>

{% endblock %}